# Generated by Django 3.1.7 on 2021-07-06 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210706_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='users',
        ),
    ]
